require('dotenv').config();
const express = require('express');
const cors = require('cors');
const resumeRoutes = require('./routes/resumeRoutes');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/resumes', resumeRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, function(){ console.log('Server listening on ' + PORT); });
